# Module 1 - Dataset Understanding

This module focuses on understanding the selected dataset before performing detailed Exploratory Data Analysis and preprocessing.

## Selected Dataset

- Dataset Name: Hotel Booking Demand Dataset
- Domain: Hospitality / Hotel Industry
- Source: Hotel Booking Demand dataset
- Target Variable: is_canceled

### Target Variable

- 1 → Booking was canceled
- 0 → Booking was not canceled

### Dataset Purpose

The dataset contains hotel booking information, including booking details, customer information, stay details, and cancellation information.

The dataset will be used to understand features, target variables, data types, and other important characteristics before performing Exploratory Data Analysis.

In [1]:
import pandas as pd

df = pd.read_csv("data/hotel_bookings.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## 1. What is a Dataset?

A dataset is a structured collection of related data organized into rows and columns. Each row represents an individual record or observation, while each column represents a feature or characteristic of that record.

### Example

In the Hotel Booking Demand dataset, each row represents one hotel booking. The columns contain information such as hotel type, arrival date, number of guests, length of stay, booking details, and cancellation status.

### Real-World Example

A hotel can use booking data to understand reservation patterns, customer behavior, stay preferences, and booking cancellations.

### Implementation

In [4]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

### Output

The output displays the first five records of the Hotel Booking Demand dataset.

### Interpretation

Each row represents one booking record, while each column represents a specific attribute related to that booking.

### Insight

The dataset contains different types of information that can be explored to identify booking patterns, customer behavior, and cancellation trends.

### AI/ML Relevance

Understanding a dataset is the first step in an AI/ML workflow. It helps identify useful features, the target variable, data types, and possible data-quality issues before preprocessing and model development.

## 2. What is a Feature?

A feature is an individual variable or column that describes a specific characteristic of a record in a dataset.

Features provide information that can be analyzed to understand patterns and, in Machine Learning, can be used as inputs for predicting a target variable.

### Example

In the Hotel Booking Demand dataset, some features include:

- Hotel type
- Lead time
- Arrival date year
- Number of adults
- Number of children
- Average daily rate
- Market segment
- Deposit type

Each feature provides different information about a hotel booking.

### Real-World Example

A hotel may use information such as booking lead time, number of guests, length of stay, and customer type to understand booking behavior.

### Implementation

In [5]:
features = df.columns

print(features)

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

### Output

The output displays all the columns available in the dataset.

### Interpretation

Each column represents a feature or attribute that describes a hotel booking record.

### Insight

The dataset contains different types of features that can be analyzed based on their data type and business meaning.

### AI/ML Relevance

Features provide the input information used by Machine Learning models to learn patterns and make predictions about the target variable.

## 3. What is a Target?

A target is the variable or outcome that we want to predict or understand using the other variables in a dataset.

In Machine Learning, the target is also called the dependent variable or output variable.

### Example

In the Hotel Booking Demand dataset, the booking cancellation status is the target.

The target tells us whether a booking was canceled or not.

### Real-World Example

A hotel may want to predict whether a future booking is likely to be canceled based on booking and customer information.

### Implementation

In [6]:
target = "is_canceled"

print("Target Variable:", target)
print(df[target].head())

Target Variable: is_canceled
0    0
1    0
2    0
3    0
4    0
Name: is_canceled, dtype: int64

### Output

The output shows the target column and its first few values.

### Interpretation

The target variable contains the outcome that we want to analyze or predict.

### Insight

The target helps define the main objective of the analysis and determines what the other features will be used to understand or predict.

### AI/ML Relevance

Identifying the target variable is an important step in Machine Learning because it defines the outcome that the model is expected to predict.

## 4. Independent Variables

Independent variables are the input variables used to understand or predict the target variable.

They are also called input variables or predictors.

### Example

In the Hotel Booking Demand dataset, variables such as lead time, number of adults, arrival details, market segment, deposit type, and previous cancellations can be used as independent variables.

These variables provide information that may help explain whether a booking will be canceled.

### Real-World Example

A hotel can use booking details, customer information, stay duration, and market segment to understand factors related to booking cancellations.

### Implementation

In [7]:
X = df.drop("is_canceled", axis=1)

print(X.head())

          hotel  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel        342               2015               July
1  Resort Hotel        737               2015               July
2  Resort Hotel          7               2015               July
3  Resort Hotel         13               2015               July
4  Resort Hotel         14               2015               July

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1
1                        27                          1
2                        27                          1
3                        27                          1
4                        27                          1

   stays_in_weekend_nights  stays_in_week_nights  adults  children  ...  \
0                        0                     0       2       0.0  ...
1                        0                     0       2       0.0  ...
2                        0                     1       1       0.0  ...
3                        0                     1       1       0.0  ...
4                        0                     2       2       0.0  ...

   deposit_type  agent company days_in_waiting_list customer_type   adr  \
0    No Deposit    NaN     NaN                    0     Transient   0.0
1    No Deposit    NaN     NaN                    0     Transient   0.0
2    No Deposit    NaN     NaN                    0     Transient  75.0
3    No Deposit  304.0     NaN                    0     Transient  75.0
4    No Deposit  240.0     NaN                    0     Transient  98.0

   required_car_parking_spaces  total_of_special_requests reservation_status  \
0                            0                          0          Check-Out
1                            0                          0          Check-Out
2                            0                          0          Check-Out
3                            0                          0          Check-Out
4                            0                          1          Check-Out

  reservation_status_date
0              2015-07-01
1              2015-07-01
2              2015-07-02
3              2015-07-02
4              2015-07-03

[5 rows x 31 columns]

### Output

The output displays the dataset after removing the target variable.

### Interpretation

The remaining columns represent the input variables that can be analyzed to understand the booking outcome.

### Insight

Different booking and customer-related variables may contain useful information about cancellation behavior.

### AI/ML Relevance

Independent variables provide the input data that a Machine Learning model uses to learn patterns and predict the target variable.

## 5. Dependent Variables

A dependent variable is the variable whose value is influenced by or depends on other variables in the dataset.

In Machine Learning, the dependent variable is generally the target or output that we want to predict.

### Example

In the Hotel Booking Demand dataset, the booking cancellation status is the dependent variable.

The other booking and customer-related variables can be used to understand factors associated with the cancellation outcome.

### Real-World Example

A hotel may study how booking details, customer type, and stay information are related to whether a reservation is canceled.

### Implementation

In [8]:
y = df["is_canceled"]

print(y.head())

0    0
1    0
2    0
3    0
4    0
Name: is_canceled, dtype: int64

### Output

The output displays the first few values of the dependent variable.

### Interpretation

Each value represents the cancellation status of a hotel booking.

### Insight

The dependent variable represents the outcome that we want to understand from the available booking data.

### AI/ML Relevance

Identifying the dependent variable helps define the prediction problem and separates the expected output from the input features used by a Machine Learning model.

## 6. Numerical Features

Numerical features are variables that contain numeric values and can be used for mathematical calculations and statistical analysis.

### Example

In the Hotel Booking Demand dataset, numerical features include age-related values, lead time, number of adults, number of children, length of stay, and average daily rate.

These values can be measured, compared, and analyzed using statistical methods.

### Real-World Example

A hotel can analyze the average daily rate, number of guests, and length of stay to understand pricing and booking patterns.

### Implementation

In [9]:
numerical_columns = df.select_dtypes(include="number").columns

print(numerical_columns)

Index(['is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_week_number', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests'],
      dtype='str')

### Output

The output displays the columns that contain numerical data.

### Interpretation

These columns contain numeric values that can be used for calculations such as mean, median, minimum, maximum, and standard deviation.

### Insight

Numerical features help us understand measurable aspects of hotel bookings and can reveal useful patterns in the dataset.

### AI/ML Relevance

Numerical features are commonly used as model inputs and may require scaling or transformation during Machine Learning preprocessing.

## 7. Categorical Features

Categorical features are variables that contain values representing groups, labels, or categories rather than numerical measurements.

### Example

In the Hotel Booking Demand dataset, categorical features include hotel type, meal type, market segment, distribution channel, customer type, and deposit type.

These values represent different groups or categories of hotel bookings.

### Real-World Example

A hotel can analyze booking categories such as customer type, market segment, and deposit type to understand different booking patterns.

### Implementation

In [11]:
categorical_columns = df.select_dtypes(include="str").columns

print(categorical_columns)

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type', 'reservation_status',
       'reservation_status_date'],
      dtype='str')

### Output

The output displays the columns that contain categorical data.

### Interpretation

These columns contain labels or categories rather than continuous numerical values.

### Insight

Categorical features help us understand different groups of bookings and compare their patterns.

### AI/ML Relevance

Categorical features are often converted into numerical representations during Machine Learning preprocessing so that models can use them as input variables.

## 8. Discrete Features

Discrete features contain countable values, usually whole numbers.

These values represent quantities that can be counted, such as the number of guests, bookings, or support requests.

### Example

In the Hotel Booking Demand dataset, adults, children, babies, and previous cancellations can be treated as discrete features because they represent countable values.

### Real-World Example

A hotel can analyze the number of adults, children, or previous cancellations to understand booking patterns and customer behavior.

### Implementation

In [12]:
discrete_columns = ["adults", "children", "babies", "previous_cancellations"]

print(df[discrete_columns].head())

   adults  children  babies  previous_cancellations
0       2       0.0       0                       0
1       2       0.0       0                       0
2       1       0.0       0                       0
3       1       0.0       0                       0
4       2       0.0       0                       0

### Output

The output displays the values of the selected discrete features for the first few booking records.

### Interpretation

These features contain countable values that represent the number of people or events associated with each booking.

### Insight

Discrete features help us understand the size and frequency of different booking-related events.

### AI/ML Relevance

Discrete features can be used as input variables in Machine Learning models to identify patterns and improve predictions.

## 9. Continuous Features

Continuous features can take a range of numerical values, including decimal values.

These features are generally measured rather than counted.

### Example

In the Hotel Booking Demand dataset, average daily rate and total room revenue can be treated as continuous features because they can contain decimal values.

### Real-World Example

A hotel can analyze room rates and total charges to understand pricing patterns and revenue-related trends.

### Implementation

In [19]:
continuous_columns = ["adr"]

print(df[continuous_columns].head())

    adr
0   0.0
1   0.0
2  75.0
3  75.0
4  98.0

### Output

The output displays the values of the average daily rate for the first few booking records.

### Interpretation

The adr column contains numerical values that can vary across a range and may include decimal values.

### Insight

Continuous features help identify differences in pricing and other measurable characteristics across hotel bookings.

### AI/ML Relevance

Continuous features can be used as input variables in Machine Learning models and may require scaling or transformation depending on the algorithm.

In [14]:
id_columns = ["agent", "company"]

print(df[id_columns].head())

   agent  company
0    NaN      NaN
1    NaN      NaN
2    NaN      NaN
3  304.0      NaN
4  240.0      NaN

## 10. Identifier Columns

An identifier column is a variable used to uniquely identify a record or entity.

The Hotel Booking Demand dataset does not contain a dedicated unique booking ID column in the standard dataset.

Columns such as agent and company identify related entities or booking sources, but they should not automatically be treated as unique record identifiers.

### Real-World Example

A hotel booking system may assign a unique Booking ID to every reservation so that each reservation can be tracked separately.

### AI/ML Relevance

Identifier columns usually do not provide meaningful predictive information and should be evaluated carefully before being used as Machine Learning features.

### Implementation

In [20]:
print(df[["agent", "company"]].head())

   agent  company
0    NaN      NaN
1    NaN      NaN
2    NaN      NaN
3  304.0      NaN
4  240.0      NaN

### Output

The output displays the values of the selected identifier-related columns.

### Interpretation

These columns are used to identify or reference booking records or related entities rather than directly describe the booking outcome.

### Insight

Identifier columns should be reviewed carefully because some identifiers may not provide meaningful information for analysis.

### AI/ML Relevance

Identifier columns are generally not useful as predictive features unless they contain meaningful information, because unique identifiers can cause a Machine Learning model to learn irrelevant patterns.

## 11. Target Variable

A target variable is the output that a Machine Learning model tries to predict.

The target variable helps define the main objective of the analysis and separates the expected outcome from the input features.

### Example

In the Hotel Booking Demand dataset, is_canceled is the target variable.

- 1 → Booking was canceled
- 0 → Booking was not canceled

### Real-World Example

A hotel can use booking information to predict whether a future reservation is likely to be canceled.

### Implementation

In [15]:
target = "is_canceled"

print(df[target].head())
print(df[target].value_counts())

0    0
1    0
2    0
3    0
4    0
Name: is_canceled, dtype: int64
is_canceled
0    75166
1    44224
Name: count, dtype: int64

### Output

The output shows the first few values of the target variable and the number of canceled and non-canceled bookings.

### Interpretation

The target variable contains two possible outcomes: canceled and not canceled bookings.

### Insight

The distribution of the target values helps us understand whether the dataset has a balanced or imbalanced target.

### AI/ML Relevance

Identifying the target variable is essential for defining a Machine Learning problem and selecting the appropriate modeling approach.

## 12. Metadata

Metadata is information that describes a dataset and helps us understand its structure, contents, and important characteristics.

It can include the dataset size, column names, data types, missing values, and other information about the data.

### Example

For the Hotel Booking Demand dataset, metadata includes the number of records, number of columns, column names, and data types.

### Real-World Example

A hotel analytics team can use metadata to quickly understand what information is available in a booking dataset before starting analysis.

### Implementation

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 37.9 MB

### Output

The output provides a summary of the dataset, including the number of rows, columns, non-null values, and data types.

### Interpretation

The dataset structure can be understood from the information provided by `info()`.

It helps identify numerical and categorical columns and also highlights columns that contain missing values.

### Insight

Metadata provides a quick overview of the dataset and helps identify areas that may require further investigation during EDA.

### AI/ML Relevance

Understanding metadata helps determine which features are suitable for analysis, which columns contain missing values, and what preprocessing may be required before Machine Learning.

## 13. Dataset Dimensions

Dataset dimensions describe the number of rows and columns present in a dataset.

Rows represent individual records, while columns represent features or variables.

### Example

In the Hotel Booking Demand dataset, each row represents a hotel booking record, and each column represents information related to that booking.

### Real-World Example

A hotel can understand how many booking records are available and how many different attributes are recorded for each booking.

### Implementation

In [17]:
print("Dataset Shape:", df.shape)
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Dataset Shape: (119390, 32)
Number of Rows: 119390
Number of Columns: 32

### Output

The output displays the total number of rows and columns in the dataset.

### Interpretation

The shape of the dataset is represented as `(rows, columns)`. The first value shows the number of records, and the second value shows the number of features.

### Insight

Understanding dataset dimensions helps us know the size of the data before performing further analysis.

### AI/ML Relevance

Dataset dimensions help determine the number of observations and available features for data analysis and Machine Learning.